"""create converter tables

Revision ID: 9ac7343f8a2a
Revises: 4aaeb2bd1635
Create Date: 2026-09-26 18:02:32.117358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac7343f8a2a'
down_revision: Union[str, Sequence[str], None] = '4aaeb2bd1635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('code_reference', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('converter_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('local_lingo', sa.String(length=200), nullable=True),
    sa.Column('monolith_weight_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pt_ppm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pd_ppm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rh_ppm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_converters_brand_id'), 'converters', ['brand_id'], unique=False)
    op.create_index(op.f('ix_converters_code_reference'), 'converters', ['code_reference'], unique=False)
    op.create_index(op.f('ix_converters_id'), 'converters', ['id'], unique=False)
    op.create_index(op.f('ix_converters_local_lingo'), 'converters', ['local_lingo'], unique=False)
    op.create_index(op.f('ix_converters_model'), 'converters', ['model'], unique=False)
    op.create_table('converter_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('converter_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converter_id'], ['converters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_converter_images_converter_id'), 'converter_images', ['converter_id'], unique=False)
    op.create_index(op.f('ix_converter_images_id'), 'converter_images', ['id'], unique=False)
    op.create_table('converter_markings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('converter_id', sa.Integer(), nullable=False),
    sa.Column('marking', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converter_id'], ['converters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_converter_markings_converter_id'), 'converter_markings', ['converter_id'], unique=False)
    op.create_index(op.f('ix_converter_markings_id'), 'converter_markings', ['id'], unique=False)
    op.create_index(op.f('ix_converter_markings_marking'), 'converter_markings', ['marking'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_converter_markings_marking'), table_name='converter_markings')
    op.drop_index(op.f('ix_converter_markings_id'), table_name='converter_markings')
    op.drop_index(op.f('ix_converter_markings_converter_id'), table_name='converter_markings')
    op.drop_table('converter_markings')
    op.drop_index(op.f('ix_converter_images_id'), table_name='converter_images')
    op.drop_index(op.f('ix_converter_images_converter_id'), table_name='converter_images')
    op.drop_table('converter_images')
    op.drop_index(op.f('ix_converters_model'), table_name='converters')
    op.drop_index(op.f('ix_converters_local_lingo'), table_name='converters')
    op.drop_index(op.f('ix_converters_id'), table_name='converters')
    op.drop_index(op.f('ix_converters_code_reference'), table_name='converters')
    op.drop_index(op.f('ix_converters_brand_id'), table_name='converters')
    op.drop_table('converters')
    # ### end Alembic commands ###
