"""add external id to brands

Revision ID: dc466fe21fd4
Revises: 9ac7343f8a2a
Create Date: 2026-10-07 02:11:11.048164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc466fe21fd4'
down_revision: Union[str, Sequence[str], None] = '9ac7343f8a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('external_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_brands_external_id'), 'brands', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_external_id'), table_name='brands')
    op.drop_column('brands', 'external_id')
    # ### end Alembic commands ###
